### ISSUE TITLE
workspace plugin not updating when switching windows

### ISSUE THREAD

**Issue by callmewoem** [adishourya/wayland_dotfiles#1]
i have tried to modify your workspace widget and for some reason it does not update when i switch windows but does run on first launch

**eww.yuck**
![image](https://user-images.githubusercontent.com/73164974/202870455-a444932d-af89-4941-aeb2-1dd1f97e55eb.png)
**workspace**
![image](https://user-images.githubusercontent.com/73164974/202870472-0629952d-af44-4ef1-ac0f-b30b075ccc52.png)

any help would be appreciated

**Comment by adishourya** [comment]
can you take a look at this: https://github.com/taylor85345/garden-hyprland-theme/blob/8b357198ae122ea7a49e3c2960b79c0a2f0d3f7c/eww/scripts/workspace

Let me know if it is of any help.

**Comment by saltnpepper97** [comment]
I have tested the provided config and I can confirm it works much better.
