### ISSUE TITLE
scss parsing error

### ISSUE THREAD

**Issue by maikelthedev** [adishourya/wayland_dotfiles#2]
I'm getting

SCSS parsing error: Error: Expected identifier.
    ╷
136 │ .0, .01, .02, .03, .04, .05, .06,
    │  ^
    ╵
./stdin:136:2

when I try to load this, it refes to eww.scss

**Comment by adishourya** [comment]
Hi.. 
I am afraid my config only works with the old eww and hyprland.
And i don't feel the need to upgrade them. So I cant really help with your parsing error.
